# Generated by Django 4.1.7 on 2023-03-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_take', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registros',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255, null=True)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
